spring.application.name=ticket-management-system
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket-management
spring.datasource.username=postgres
spring.datasource.password=2002
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true